name: Makefile CI

on:
  push:
    branches: [ "openwrt-21.02" ]
  pull_request:
    branches: [ "openwrt-21.02" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: feed update
      run: ./scripts/feeds update -a

    - name: feed install
      run: ./scripts/feeds install -a

    - name: cp cfg
      run: cp -f defconfig/mt7986-ax6000.config .config

    - name: make menuconfig
      run: make menuconfig
      
    - name: Install dependencies
      run: make
